version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  url_shortener:
    build: .
    container_name: url_shortener
    ports:
      - "5000:5000"
    depends_on:
      - redis
