apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z redis-svc 6379; do echo waiting for redis; sleep 2; done;']
      containers:
      - name: url-shortener-container
        image: pes2ug22cs524/url_shortener_app_17:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: "redis-svc"
          - name: BASE_URL
            value: "http://127.0.0.1:80/"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
